# Generated by Django 3.2 on 2021-12-01 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='メソッド')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('exp1', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明１')),
                ('exp2', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明２')),
                ('i_type', models.SmallIntegerField(default=1, verbose_name='入力形式')),
                ('o_type', models.SmallIntegerField(default=1, verbose_name='出力形式')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状態')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name_plural': 'アクション',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='メソッド')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('exp1', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明１')),
                ('exp2', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明２')),
            ],
            options={
                'verbose_name_plural': '条件',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('exp1', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明１')),
                ('exp2', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明２')),
            ],
            options={
                'verbose_name_plural': 'フロー',
            },
        ),
        migrations.CreateModel(
            name='FlowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execno', models.SmallIntegerField(verbose_name='実行NO')),
                ('next_execno', models.SmallIntegerField(blank=True, null=True, verbose_name='後続実行NO')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.action', verbose_name='アクション')),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.flow', verbose_name='フロー')),
            ],
            options={
                'verbose_name_plural': 'フロー明細',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='キー名')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='キー')),
                ('exp1', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明１')),
                ('exp2', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明２')),
            ],
            options={
                'verbose_name_plural': 'キー',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=255, null=True, verbose_name='表記名（略）')),
                ('fname', models.CharField(max_length=255, verbose_name='表記名')),
                ('module', models.CharField(max_length=255, verbose_name='モジュール')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状態')),
                ('is_active', models.BooleanField(default=False, verbose_name='利用可')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name_plural': 'サービス',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intval', models.SmallIntegerField(blank=True, default=0, verbose_name='実行間隔（分）')),
                ('date', models.CharField(blank=True, max_length=8, null=True, verbose_name='実行日')),
                ('time', models.CharField(blank=True, max_length=4, null=True, verbose_name='実行時間')),
                ('week', models.CharField(blank=True, max_length=7, null=True, verbose_name='実行曜日')),
                ('s_from', models.CharField(blank=True, max_length=8, null=True, verbose_name='開始日')),
                ('s_to', models.CharField(blank=True, max_length=8, null=True, verbose_name='終了日')),
                ('status', models.SmallIntegerField(blank=True, default=0, verbose_name='状態')),
                ('exec_at', models.CharField(blank=True, max_length=17, null=True, verbose_name='最終実行日時')),
                ('err_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='エラーメッセージ')),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.flow', verbose_name='フロー')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'スケジュール',
            },
        ),
        migrations.CreateModel(
            name='IndividualKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=255, null=True, verbose_name='文字列')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('text', models.TextField(blank=True, null=True, verbose_name='フリー')),
                ('bool', models.BooleanField(verbose_name='ON/OFF')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数値')),
                ('flowdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.flowdetail', verbose_name='フロー明細')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.key', verbose_name='アクションキー')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '個別キー設定',
            },
        ),
        migrations.CreateModel(
            name='IndividualConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_execno', models.SmallIntegerField(blank=True, null=True, verbose_name='後続実行NO')),
                ('priority', models.SmallIntegerField(blank=True, null=True, verbose_name='実行順')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.condition', verbose_name='条件')),
                ('flowdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.flowdetail', verbose_name='フロー明細')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '個別条件設定',
            },
        ),
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('oa', models.CharField(blank=True, max_length=255, null=True)),
                ('nk', models.CharField(blank=True, max_length=255, null=True)),
                ('np', models.CharField(blank=True, max_length=255, null=True)),
                ('tk', models.CharField(blank=True, max_length=255, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終更新日時')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.service', verbose_name='サービス')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '認証',
            },
        ),
        migrations.CreateModel(
            name='ActionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.action', verbose_name='アクション')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.key', verbose_name='キー')),
            ],
            options={
                'verbose_name_plural': 'アクションキー',
            },
        ),
        migrations.CreateModel(
            name='ActionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.action', verbose_name='アクション')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.condition', verbose_name='条件')),
            ],
            options={
                'verbose_name_plural': 'アクション条件',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobflows.service', verbose_name='サービス'),
        ),
    ]
