# Generated by Django 3.2 on 2022-02-15 10:11

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='会社名')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='住所')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='電話番号')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='氏名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='最終ログイン日')),
            ],
            options={
                'verbose_name_plural': 'ユーザ',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
